// WARNING: Do NOT edit the input and output ports in this file in a text
// editor if you plan to continue editing the block that represents it in
// the Block Editor! File corruption is VERY likely to occur.

// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions
// and other software and tools, and any partner logic
// functions, and any output files from any of the foregoing
// (including device programming or simulation files), and any
// associated documentation or information are expressly subject
// to the terms and conditions of the Intel Program License
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 917 02/14/2023)
// Created on Tue Feb 20 09:26:01 2024

//  Module Declaration
module seven_seg_decoder
(
// {{ALTERA_ARGS_BEGIN}} DO NOT REMOVE THIS LINE!
x0, x1, x2, x3, a, b, c, d, e, f, g
// {{ALTERA_ARGS_END}} DO NOT REMOVE THIS LINE!
);
// Port Declaration

// {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
input x0;
input x1;
input x2;
input x3;
output a;
output b;
output c;
output d;
output e;
output f;
output g;
// {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!

reg a, b, c, d, e, f, g;

always @(x3 or x2 or x1 or x0)
begin
	case({x3, x2, x1, x0})
		4'b0000: begin
			a='b0;
			b='b0;
			c='b0;
			d='b0;
			e='b0;
			f='b0;
			g='b1;
		end
		
		4'b0001: begin
			a='b1;
			b='b0;
			c='b0;
			d='b1;
			e='b1;
			f='b1;
			g='b1;
		end
		
		4'b0010: begin
			a='b0;
			b='b0;
			c='b1;
			d='b0;
			e='b0;
			f='b1;
			g='b0;
		end
		
		4'b0011: begin
			a='b0;
			b='b0;
			c='b0;
			d='b0;
			e='b1;
			f='b1;
			g='b0;
		end
		
		4'b0100: begin
			a='b1;
			b='b0;
			c='b0;
			d='b1;
			e='b1;
			f='b0;
			g='b0;
		end
		
		4'b0101: begin
			a='b0;
			b='b1;
			c='b0;
			d='b0;
			e='b1;
			f='b0;
			g='b0;
		end
		
		4'b0110: begin
			a='b0;
			b='b1;
			c='b0;
			d='b0;
			e='b0;
			f='b0;
			g='b0;
		end
		
		4'b0111: begin
			a='b0;
			b='b0;
			c='b0;
			d='b1;
			e='b1;
			f='b1;
			g='b1;
		end
		
		4'b1000: begin
			a='b0;
			b='b0;
			c='b0;
			d='b0;
			e='b0;
			f='b0;
			g='b0;
		end
		
		4'b1001: begin
			a='b0;
			b='b0;
			c='b0;
			d='b0;
			e='b1;
			f='b0;
			g='b0;
		end
		
		4'b1010: begin
			a='b0;
			b='b0;
			c='b0;
			d='b1;
			e='b0;
			f='b0;
			g='b0;
		end
		
		4'b1011: begin
			a='b1;
			b='b1;
			c='b0;
			d='b0;
			e='b0;
			f='b0;
			g='b0;
		end
		
		4'b1100: begin
			a='b0;
			b='b1;
			c='b1;
			d='b0;
			e='b0;
			f='b0;
			g='b1;
		end
		
		4'b1101: begin
			a='b1;
			b='b0;
			c='b0;
			d='b0;
			e='b0;
			f='b1;
			g='b0;
		end
		
		4'b1110: begin
			a='b0;
			b='b1;
			c='b1;
			d='b0;
			e='b0;
			f='b0;
			g='b0;
		end
		
		4'b1111: begin
			a='b0;
			b='b1;
			c='b1;
			d='b1;
			e='b0;
			f='b0;
			g='b0;
		end
	endcase
end


endmodule
